src/Application.vala, src/MainWindow.vala
Adds a few more shortcuts and sets up columns:
=> Fill out and set up columns

src/Application.vala, src/MainWindow.vala, src/ShortcutEntry.vala
This adds screenshot-related shortcuts
=> Screenshots

src/MainWindow.vala
This should cover what Cassidy listed in the doc in the README
=> Add missing Window and Workspace shortcuts

src/MainWindow.vala
Change "Applications" category to "System" and add zoom shortcuts
=> Add zoom shortcuts

src/MainWindow.vala
This adds a few system shortcuts as discussed with @cassidyjames
=> Add more system shortcuts

src/MainWindow.vala
=> Set skip taskbar hint

meson.build, src/Application.vala
=> Don't exit on focus-out when running from Terminal

src/Views/ShortcutsView.vala
Fixes #32.
Adds the PiP shortcut.
=> Add PiP shortcut

.travis.yml
I think this should fix builds maybe?
=> Update Travis for Houston

src/Views/ShortcutsView.vala
As mentioned [here](https://github.com/elementary/switchboard-plug-keyboard/pull/187#pullrequestreview-174591347).
=> Adds close to windows entries

debian/control
=> Control: Add handy dep

src/Views/ShortcutsView.vala
=> Add all screenshot shortcuts

data/shortcut-overlay.appdata.xml.in, data/shortcut-overlay.desktop.in, src/MainWindow.vala
=> MainWindow: Shorten title to 'Shortcuts'

src/Views/ShortcutsView.vala
Fixes #121 
Goes with https://github.com/elementary/gala/pull/1411
=> Read screenshot shortcuts from gala schema

src/MainWindow.vala
=> MainWindow: Fix typo

src/Views/ShortcutsView.vala
=> Show on-screen keyboard shortcut

data/shortcut-overlay.desktop.in
=> Re-show in Applications Menu

src/Views/ShortcutsView.vala
https://github.com/elementary/gala/pull/2032
=> Use new keybindings schema

debian/control
=> control: Require libgranite-7-dev >= 7.3.0

data/shortcut-overlay.metainfo.xml.in, meson.build
=> Release 8.1.0
